funny
tekoh/nypsi pull request #1278
Opened 2023-10-06 17:57 UTC by Bulvius1

2023-10-06 18:03 UTC, tekoh requested changes

2023-10-06 18:03 UTC, tekoh commented on src/commands/Funny
> +const cmd = new Command("funny", "measure how much funny u are", "fun").setAliases([
fix grammar

2023-10-06 18:03 UTC, tekoh commented on src/commands/Funny
> +cmd.slashData.addUserOption((option) =>
no slash command needed - remove

2023-10-06 18:03 UTC, tekoh commented on src/commands/Funny
> +    funnyText = "you're unfunny, but have 1 xp";
grammar

2023-10-06 18:03 UTC, tekoh commented on src/commands/funny
why create two files?? delete this one and make the other one lowercase + it needs file extension

2023-10-06 18:28 UTC, tekoh requested changes
you still havent made the changes i requested. why did you request a review?

2023-10-06 18:32 UTC, Bulvius1 commented on src/commands/Funny
> +const cmd = new Command("funny", "measure how much funny u are", "fun").setAliases([
Fixed

2023-10-06 18:32 UTC, Bulvius1 commented on src/commands/Funny
> +    funnyText = "you're unfunny, but have 1 xp";
fixed

2023-10-06 18:32 UTC, Bulvius1 commented on src/commands/funny
ok sorry

2023-10-06 18:32 UTC, Bulvius1 commented on src/commands/Funny
> +cmd.slashData.addUserOption((option) =>
i hope this works

2023-10-07 23:21 UTC, tekoh requested changes
still broken

2023-10-11 22:35 UTC, tekoh commented
closing bc unresponsive

2023-10-11 22:35 UTC, closed without merging